apiVersion: batch/v1
kind: CronJob
metadata:
  name: geojson-analysis
spec:
  schedule: "0 2 * * *"
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pyspark-container
              image: geoanalysis-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
