apiVersion: batch/v1
kind: CronJob
metadata:
  name: expansion-exploitation-cronjob
spec:
  schedule: "0 1 * * *"
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pyspark-container
              image: exploitation-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
