apiVersion: batch/v1
kind: CronJob
metadata:
  name: expansion-trusted-cronjob
spec:
  schedule: "15 0 * * *"
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pyspark-container
              image: trusted-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
