apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-cronjob
spec:
  schedule: "0 * * * *"
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: python-container
              image: python-code-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
