apiVersion: batch/v1
kind: CronJob
metadata:
  name: stream-estat-estacions-cronjob
spec:
  schedule: "* * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: stream-estat-estacions-container
              image: stream-estat-estacions-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
