apiVersion: batch/v1
kind: CronJob
metadata:
  name: optimal-route-cronjob
spec:
  schedule: "* * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: optimal-route-container
              image: optimal-route-image:latest
              imagePullPolicy: Never
          restartPolicy: Never
